### ISSUE TITLE
How can we add tab in form uicomponent

### ISSUE THREAD

**Issue by Rutvee123** [astorm/magento2-pestle-platonic-module-output#4]
<item name="layout" xsi:type="array">
            <item name="type" xsi:type="string">tabs</item>
            <item name="navContainerName" xsi:type="string">left</item>
        </item>

**Comment by astorm** [comment]
@Rutvee123 It's not clear what you're asking -- but is there a specific form that already exists in Magento 2 that you're trying to emulate?
